version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - webnet
      - database

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: uservendas
      POSTGRES_PASSWORD: passvendas
      POSTGRES_DB: venda
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet:
  database:
