name: CI Pipeline

on:
  push:
    branches:
      - main  # Aciona o workflow para qualquer push em qualquer branch
  pull_request:
    branches:
      - main  # Aciona o workflow para PRs que visam a branch main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Substitua pela versão do Python que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Substitua 'tests' pelo diretório dos seus testes

